gzip dumps before upload. Gives us a >10x size reduction

diff --git a/pg-b2 b/pg-b2
--- a/pg-b2
+++ b/pg-b2
@@ -1,7 +1,8 @@
 #!/bin/bash
-# Takes a pg_dump of a file and uploads it to Backblaze B2.
+# gzips a pg_dump of a table and uploads it to Backblaze B2.
 
 set -e
+set pipefail
 
 die() {
     echo "Fatal: $*" >&2
@@ -34,13 +35,13 @@ BASEDIR="${HOME:-/tmp}"
 PGB2_SCRATCH_DIR="${PGB2_SCRATCH_DIR:-$BASEDIR/.pgb2_scratch}"
 
 mkdir -p "$PGB2_SCRATCH_DIR" || die "failed to make scratch dir"
-DUMPLOC="$(mktemp "${PGB2_SCRATCH_DIR}/pgdump.XXXXXX")" \
+DUMPLOC="$(mktemp "${PGB2_SCRATCH_DIR}/pgdump.XXXXXX.gz")" \
     || die "failed to make pgdump file"
 
 # shellcheck disable=SC2064
 trap "echo cleaning up '$DUMPLOC'; rm '$DUMPLOC'" EXIT
 
-pg_dump "$TABLE_NAME" > "$DUMPLOC" || die "failed to dump $TABLE_NAME"
+pg_dump "$TABLE_NAME" | gzip > "$DUMPLOC" || die "failed to dump $TABLE_NAME"
 
 FN="$FN_PREFIX$TABLE_NAME.pgdump"
 echo "trying to upload <$DUMPLOC> to <$BUCKET_NAME:$FN>..."
